# Generated by Django 4.2.3 on 2023-07-28 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_rename_is_active_version_current_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='current_version',
            new_name='active_version',
        ),
    ]
